spring.datasource.url=jdbc:postgresql://localhost:5432/notes_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update

# Secret key (Must be at least 256 bits / 32 characters long)
jwt.secret=enebolminiisuperduperhamgiinurtsecretforlearningcodewritingthisnotworkingformenotgettingto256bits
jwt.expiration=86400000